1154 add cross browser testing
GSA/px-benefit-finder pull request #1207
Opened 2024-04-15 16:48 UTC by nehemiah-abuga

## PR Summary

This PR configures benefit-finder project for cross browser testing to validate current implement functionality.
Tests to run on Chrome, Edge, Firefox and WebKit(Safari).

## Related Github Issue

- Fixes #1154 

## Detailed Testing steps
- [ ] Ensure you have chrome, edge, and firefox installed on your local machine
- [ ] pull changes locally
- [ ] `cd benefit finder`
- [ ] `npm install`
- [ ] `npm run dev:storybook"
- [ ] `npm run cy:run:cross-browser:e2e`
- [ ] Verify tests run in chrome, edge, firebox and safari webkit

2024-04-17 17:22 UTC, scottqueen-bixal requested changes

2024-04-17 17:22 UTC, scottqueen-bixal commented on .github/workflows/build-and-deploy.yml
these changes shouldn't be necessary since they are already on dev

https://github.com/GSA/px-benefit-finder/blob/dev/.github/workflows/build-and-deploy.yml

2024-04-17 17:28 UTC, scottqueen-bixal requested changes

2024-04-17 17:28 UTC, scottqueen-bixal commented on benefit-finder/package.json
> +    "cy:run:edge:e2e": "NODE_ENV=test npx cypress run --browser edge",
why do we pass these browser flags instead of just configuring in the pipeline with the action?

https://glebbahmutov.com/blog/cypress-webkit/

2024-04-18 20:50 UTC, nehemiah-abuga commented on .github/workflows/build-and-deploy.yml
We dont need this PR as local and pipeline changes are in https://github.com/GSA/px-benefit-finder/pull/1209

2024-04-18 20:50 UTC, closed without merging